version: "3.8"

services:
  geocodeur-db:
    image: "postgis/postgis:17-3.5-alpine"
    container_name: "geocodeur-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geocodeur
    ports:
      - "5432:5432"
    volumes:
      - geocodeur_data:/var/lib/postgresql/data

volumes:
  geocodeur_data:
    driver: local
