services:
  meilisearch:
    image: "getmeili/meilisearch:v1.12"
    container_name: "meilisearch"
    environment:
      MEILI_MASTER_KEY: E8H-DDQUGhZhFWhTq263Ohd80UErhFmLIFnlQK81oeQ
      MEILI_NO_ANALYTICS: true
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data

volumes:
  geocodeur_data:
    driver: local
